"""add click_count to opportunities

Revision ID: c51d2b76b592
Revises: 4a32ad976fd3
Create Date: 2026-07-21 07:55:08.748556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c51d2b76b592'
down_revision: Union[str, Sequence[str], None] = '4a32ad976fd3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; NOT NULL is then safe
    op.add_column('opportunities', sa.Column('click_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('opportunities', 'click_count')
    # ### end Alembic commands ###
